delete from dbo.Properties;
delete from dbo.Owners;
delete from dbo.Tenants;
dbcc checkident ('dbo.Owners', RESEED, 0)
dbcc checkident ('dbo.Tenants', RESEED, 0)
dbcc checkident ('dbo.Properties', RESEED, 0)

insert into dbo.Owners (Name) values ('Gaspar Warin');
insert into dbo.Owners (Name) values ('Lotti Pree');
insert into dbo.Owners (Name) values ('Abbott Thorold');
insert into dbo.Owners (Name) values ('Odessa Drowsfield');
insert into dbo.Owners (Name) values ('Benetta Roughley');
insert into dbo.Owners (Name) values ('Francklyn Hadgkiss');
insert into dbo.Owners (Name) values ('Virgina Luciani');
insert into dbo.Owners (Name) values ('Katti Sadgrove');
insert into dbo.Owners (Name) values ('Dora Tiddeman');
insert into dbo.Owners (Name) values ('Andriana Decourcy');
insert into dbo.Owners (Name) values ('Gayler Creavan');
insert into dbo.Owners (Name) values ('Maye Servis');
insert into dbo.Owners (Name) values ('Modesty Yersin');
insert into dbo.Owners (Name) values ('Rutger Haugeh');
insert into dbo.Owners (Name) values ('Wheeler Jiri');
insert into dbo.Owners (Name) values ('Gilberta Pumphreys');
insert into dbo.Owners (Name) values ('Eden Tothe');
insert into dbo.Owners (Name) values ('Vonnie Lagden');
insert into dbo.Owners (Name) values ('Junette Ortell');
insert into dbo.Owners (Name) values ('Vickie Petters');
insert into dbo.Owners (Name) values ('Marcellina Chadbourne');
insert into dbo.Owners (Name) values ('Kaylyn Pioli');
insert into dbo.Owners (Name) values ('Sandi Moughton');
insert into dbo.Owners (Name) values ('Rosemonde Beckensall');
insert into dbo.Owners (Name) values ('Devonne Cornew');
insert into dbo.Owners (Name) values ('Lukas Hayler');
insert into dbo.Owners (Name) values ('Shelton Kelland');
insert into dbo.Owners (Name) values ('Johnathan Gwynn');
insert into dbo.Owners (Name) values ('Ebenezer Verzey');
insert into dbo.Owners (Name) values ('Frasquito McNay');
insert into dbo.Owners (Name) values ('Tate Bonnick');
insert into dbo.Owners (Name) values ('Kelwin Raubenheim');
insert into dbo.Owners (Name) values ('Oralla Yuranovev');
insert into dbo.Owners (Name) values ('Amanda Fairham');
insert into dbo.Owners (Name) values ('Russell Dodds');
insert into dbo.Owners (Name) values ('Ramsey Asbrey');
insert into dbo.Owners (Name) values ('Rodger Giacopazzi');
insert into dbo.Owners (Name) values ('Meggi Tapsell');
insert into dbo.Owners (Name) values ('Pattie Poulgreen');
insert into dbo.Owners (Name) values ('Tedie Fantonetti');
insert into dbo.Owners (Name) values ('Kandy Van den Velde');
insert into dbo.Owners (Name) values ('Dione Fieldstone');
insert into dbo.Owners (Name) values ('Randene Gravey');
insert into dbo.Owners (Name) values ('Conney Sturch');
insert into dbo.Owners (Name) values ('Brnaba Orlton');
insert into dbo.Owners (Name) values ('Brittney Phalip');
insert into dbo.Owners (Name) values ('Erek Meckiff');
insert into dbo.Owners (Name) values ('Gerrilee Dyble');
insert into dbo.Owners (Name) values ('Marlena Linton');
insert into dbo.Owners (Name) values ('Meir Solly');
insert into dbo.Tenants (Name) values ('Blinni Cellone');
insert into dbo.Tenants (Name) values ('Tallie Ebbett');
insert into dbo.Tenants (Name) values ('Dayle Cottu');
insert into dbo.Tenants (Name) values ('Anallise MacGilmartin');
insert into dbo.Tenants (Name) values ('Ripley Lascelles');
insert into dbo.Tenants (Name) values ('Christie Vaines');
insert into dbo.Tenants (Name) values ('Lucias Supple');
insert into dbo.Tenants (Name) values ('Georgiana Pridie');
insert into dbo.Tenants (Name) values ('Wilburt Ben');
insert into dbo.Tenants (Name) values ('Chrissie Ludgrove');
insert into dbo.Tenants (Name) values ('Bobbie Vauter');
insert into dbo.Tenants (Name) values ('Gaylene Grcic');
insert into dbo.Tenants (Name) values ('Gwenora Wardrope');
insert into dbo.Tenants (Name) values ('Mauricio Cowgill');
insert into dbo.Tenants (Name) values ('Violette Bettesworth');
insert into dbo.Tenants (Name) values ('Catarina MacGaughy');
insert into dbo.Tenants (Name) values ('Sherry Maloney');
insert into dbo.Tenants (Name) values ('Bettine Maskill');
insert into dbo.Tenants (Name) values ('Edouard Mitton');
insert into dbo.Tenants (Name) values ('Dewain Hardi');
insert into dbo.Tenants (Name) values ('Kean Shard');
insert into dbo.Tenants (Name) values ('Jacquetta Densumbe');
insert into dbo.Tenants (Name) values ('Heddi Mancktelow');
insert into dbo.Tenants (Name) values ('Austin Drakers');
insert into dbo.Tenants (Name) values ('Sylvia McGaugey');
insert into dbo.Tenants (Name) values ('Rainer Alasdair');
insert into dbo.Tenants (Name) values ('Pansie Ferrier');
insert into dbo.Tenants (Name) values ('Aveline Kildea');
insert into dbo.Tenants (Name) values ('Gavrielle Eddis');
insert into dbo.Tenants (Name) values ('Mignon Bagg');
insert into dbo.Tenants (Name) values ('Morgen Napleton');
insert into dbo.Tenants (Name) values ('Cindie Phelps');
insert into dbo.Tenants (Name) values ('Gabriello Whitnall');
insert into dbo.Tenants (Name) values ('Demetri Iliff');
insert into dbo.Tenants (Name) values ('Neely O''Fairy');
insert into dbo.Tenants (Name) values ('Genia Croote');
insert into dbo.Tenants (Name) values ('Petra Paulet');
insert into dbo.Tenants (Name) values ('Flori O''Doghesty');
insert into dbo.Tenants (Name) values ('Nydia Yerrill');
insert into dbo.Tenants (Name) values ('Immanuel Dukes');
insert into dbo.Tenants (Name) values ('Georgetta Burkert');
insert into dbo.Tenants (Name) values ('Mady MacGovern');
insert into dbo.Tenants (Name) values ('Ramsay Goodfellow');
insert into dbo.Tenants (Name) values ('Shermy Coggings');
insert into dbo.Tenants (Name) values ('Brannon Liddon');
insert into dbo.Tenants (Name) values ('Gertie Gammage');
insert into dbo.Tenants (Name) values ('Emilee Randalson');
insert into dbo.Tenants (Name) values ('Agnesse Raggitt');
insert into dbo.Tenants (Name) values ('Ingeborg Tonks');
insert into dbo.Tenants (Name) values ('Melli Zanitti');
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('48699 Vernon Way', 35, 23, 1169.73);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('7 Merchant Junction', 36, 2, 3412.06);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('0587 Messerschmidt Center', 47, 11, 3291.03);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('83984 Gerald Trail', 48, 47, 4022.99);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6 Helena Drive', 10, 43, 2282.42);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('840 Service Point', 13, 23, 2186.7);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('833 Melrose Pass', 36, 34, 2962.81);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2227 Sachs Place', 14, 20, 3161.6);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('126 Cody Terrace', 11, 2, 2967.53);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('50 Saint Paul Terrace', 49, 41, 1473.58);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('536 Upham Park', 13, 7, 1000.69);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('201 Rowland Court', 5, 11, 1908.05);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('16861 Hollow Ridge Crossing', 37, 33, 4252.69);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('078 Crowley Lane', 45, 24, 3891.62);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('600 Dovetail Center', 23, 24, 1922.02);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('99684 Shopko Trail', 45, 45, 3202.94);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('27 Trailsway Point', 46, 48, 4096.33);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('415 Arapahoe Junction', 25, 17, 3659.04);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('40 Schiller Hill', 28, 43, 1142.56);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('882 Claremont Circle', 42, 42, 1938.13);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('1 Lukken Court', 1, 38, 2674.75);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('36872 Northwestern Way', 43, 15, 1818.63);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('83898 Mayer Plaza', 1, 34, 2669.25);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('7 Hazelcrest Crossing', 37, 28, 4282.99);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('45 Claremont Park', 8, 30, 3259.22);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('346 Sachs Pass', 44, 21, 4499.62);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('66 Marquette Park', 36, 3, 1508.73);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('8183 Oak Valley Street', 12, 9, 2537.97);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2 Johnson Place', 44, 41, 3294.64);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5428 Springview Point', 33, 17, 3362.75);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('78873 Towne Place', 9, 48, 1173.03);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4 Kennedy Terrace', 4, 17, 1974.79);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('85 Helena Lane', 48, 12, 1262.25);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('94 Victoria Pass', 15, 10, 2636.6);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('03465 Warrior Drive', 5, 30, 1172.07);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('9 Sauthoff Junction', 17, 6, 2078.11);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('331 Old Shore Way', 24, 14, 1656.28);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6 Northland Center', 29, 44, 4382.31);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('1639 Blackbird Center', 5, 3, 4321.66);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('8 Northland Alley', 40, 28, 1255.71);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('388 Fairfield Plaza', 17, 26, 4312.62);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('77768 Meadow Valley Alley', 32, 21, 3272.53);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('9 Truax Road', 28, 36, 4209.75);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('1 Banding Trail', 27, 34, 1056.49);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5696 Thierer Point', 11, 44, 1371.69);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4 Fairview Crossing', 45, 29, 4135.95);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5 Mayer Drive', 33, 5, 4095.71);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('7 Blue Bill Park Parkway', 45, 17, 3858.93);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('67520 Forest Dale Point', 21, 48, 2383.44);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('8551 Prairie Rose Center', 18, 20, 1649.3);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('42258 Mesta Alley', 39, 3, 3952.88);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2 Mallory Junction', 20, 19, 2194.13);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('77 Cascade Avenue', 39, 23, 2766.37);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('452 Manley Court', 32, 46, 1370.19);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('79203 Bonner Pass', 22, 26, 1978.49);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('633 Waxwing Point', 43, 46, 1528.45);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2 Caliangt Circle', 47, 37, 2336.55);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('54009 Annamark Terrace', 43, 23, 2133.85);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('91670 Tomscot Point', 19, 32, 3498.78);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('746 Anhalt Road', 48, 6, 3182.12);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('34337 Emmet Pass', 25, 46, 1255.01);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2 Independence Pass', 8, 36, 3756.26);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('95430 Sullivan Crossing', 28, 42, 4108.34);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4194 Fisk Terrace', 8, 36, 1093.01);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('592 Eastlawn Hill', 14, 41, 3086.12);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('27199 School Point', 17, 22, 2145.44);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('805 Anzinger Hill', 12, 26, 3664.11);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5426 Hermina Junction', 16, 49, 3515.04);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5 Rieder Alley', 8, 49, 2721.32);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('9139 Westridge Court', 45, 49, 4340.0);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('62329 Anderson Crossing', 36, 40, 3021.57);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('887 Sunfield Way', 46, 24, 3748.06);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('44 Derek Avenue', 6, 11, 2445.66);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('0511 Londonderry Alley', 42, 44, 1628.19);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2 Towne Drive', 4, 1, 1593.47);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('803 Sauthoff Trail', 28, 14, 1805.24);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5 Dayton Way', 25, 16, 2089.93);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('456 Iowa Road', 44, 34, 2937.87);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('50 Sheridan Trail', 36, 19, 3524.67);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('019 Northland Way', 41, 4, 2623.19);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4786 Ridge Oak Court', 7, 10, 3396.83);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4502 Ilene Alley', 49, 18, 2737.28);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('71 Rockefeller Drive', 31, 39, 2016.41);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('417 Chinook Park', 5, 17, 3185.95);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('31210 Vernon Parkway', 40, 37, 2770.68);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5350 Meadow Vale Junction', 12, 47, 1768.65);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('115 American Way', 34, 6, 1011.53);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('212 Twin Pines Way', 32, 46, 3287.81);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('1 Sage Road', 34, 48, 3328.23);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('98 Esch Pass', 25, 18, 2262.29);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('74 Coleman Circle', 41, 41, 1428.18);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('0 Vermont Park', 7, 19, 2269.98);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('462 Mockingbird Place', 38, 40, 3246.33);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('16794 Larry Plaza', 41, 6, 1537.21);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('47 Hermina Circle', 17, 13, 1979.48);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('34291 Parkside Way', 13, 38, 2083.83);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('72 Corry Drive', 33, 27, 1936.14);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('21 Transport Street', 24, 26, 1414.89);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('55053 Weeping Birch Parkway', 18, 30, 1581.0);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('40312 Manley Avenue', 49, 35, 3043.72);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('38 Evergreen Avenue', 14, 42, 4155.98);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4 Welch Plaza', 18, 28, 1729.3);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('274 Ridge Oak Plaza', 18, 41, 4064.53);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('8 Stone Corner Place', 49, 6, 3865.35);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('891 Huxley Circle', 21, 11, 3154.61);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6 Superior Road', 11, 23, 4458.42);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('19 Artisan Avenue', 46, 48, 4110.68);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2852 Melody Pass', 21, 44, 2048.67);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('7579 Mitchell Street', 38, 26, 3962.1);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('0 Leroy Terrace', 24, 37, 1504.47);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('7378 Killdeer Terrace', 1, 32, 2171.3);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('9125 Pankratz Hill', 14, 20, 1655.06);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('99 Gateway Place', 45, 46, 2314.92);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('33068 Myrtle Parkway', 30, 15, 2603.87);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('00874 Washington Park', 43, 31, 2528.17);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('364 Trailsway Avenue', 20, 14, 4081.41);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('30703 East Hill', 9, 41, 1580.37);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('89 Talisman Junction', 49, 9, 2381.65);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('42 Lighthouse Bay Place', 32, 23, 4436.75);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('97 Ridgeway Circle', 6, 6, 1152.11);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('9 Schurz Terrace', 34, 47, 4199.4);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('42952 Eastwood Plaza', 11, 23, 4364.84);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('56 Huxley Parkway', 21, 22, 1968.82);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('916 Westridge Crossing', 14, 7, 2682.61);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('621 Moulton Plaza', 29, 48, 3309.13);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('3 Grim Lane', 13, 17, 1613.87);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('02257 5th Terrace', 24, 44, 3447.32);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('940 Boyd Alley', 17, 18, 4269.37);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('70 Forster Circle', 8, 35, 2222.33);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('82 Coolidge Circle', 34, 27, 3828.78);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('3143 Loomis Point', 48, 40, 1785.97);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2653 Charing Cross Circle', 33, 1, 3640.69);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2 Gateway Place', 42, 36, 3460.39);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('944 Shopko Court', 31, 44, 1271.21);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('11 Prairieview Way', 1, 15, 1626.98);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('974 Havey Hill', 31, 8, 2842.61);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('642 Melrose Place', 43, 16, 2782.07);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5527 Onsgard Trail', 50, 13, 2334.93);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('44 Melrose Avenue', 21, 6, 1699.68);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('94 Talmadge Way', 26, 16, 3044.07);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4188 Gale Avenue', 28, 2, 4364.95);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('010 Coolidge Circle', 20, 39, 1570.95);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5 Eggendart Hill', 15, 13, 2013.65);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('7 Caliangt Court', 39, 11, 1548.47);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('71 Susan Park', 48, 29, 1297.43);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('839 Green Parkway', 17, 40, 2152.43);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4 Reindahl Plaza', 27, 8, 4372.44);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('84392 Grover Plaza', 45, 40, 3406.1);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('345 Montana Crossing', 40, 20, 3313.01);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('72 Waywood Parkway', 23, 40, 1652.13);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('65 Nova Road', 18, 26, 3413.72);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4 Hoffman Street', 1, 37, 1491.13);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('22943 Twin Pines Plaza', 41, 35, 1919.89);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('024 Kingsford Lane', 2, 41, 1247.94);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('10 Esker Alley', 12, 15, 4461.87);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('3201 Thompson Circle', 23, 10, 1075.43);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6329 Shopko Parkway', 28, 44, 4008.85);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6448 4th Plaza', 16, 11, 3661.75);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2504 Rutledge Trail', 34, 31, 4385.42);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('076 Homewood Place', 4, 35, 1205.59);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('479 Larry Park', 49, 43, 2468.72);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6578 Bowman Point', 46, 34, 1459.51);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('9762 Maple Court', 34, 11, 1862.83);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4008 Nevada Pass', 24, 35, 1164.27);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6 Buhler Plaza', 15, 29, 3723.45);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6 Clemons Point', 4, 2, 1893.37);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('1796 Bartelt Drive', 18, 6, 3859.82);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('98 Lakeland Plaza', 2, 22, 2370.0);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('0820 Waxwing Trail', 34, 4, 2343.55);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('3756 Kropf Street', 1, 17, 1421.17);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('31973 Scott Point', 22, 48, 2874.01);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5134 Arrowood Hill', 19, 21, 3481.76);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('42 Ryan Plaza', 3, 49, 3007.55);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('3 Emmet Way', 24, 10, 3259.78);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('01567 Cambridge Street', 14, 16, 2583.02);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('81 Carioca Court', 2, 1, 3862.1);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('353 Marquette Center', 37, 24, 3538.07);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('24749 Loomis Crossing', 39, 43, 3503.83);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4236 Lunder Junction', 44, 48, 2508.3);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('58 Continental Way', 22, 19, 3290.91);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('49 Mitchell Point', 46, 45, 3512.8);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('2 Lien Crossing', 32, 43, 1658.76);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('97435 Maple Terrace', 5, 18, 2730.15);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('24449 Veith Place', 8, 45, 1645.82);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('705 Toban Way', 1, 45, 2282.58);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('3 Hintze Plaza', 21, 35, 3493.59);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('0670 Hoard Terrace', 5, 27, 3510.02);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('87 Heffernan Crossing', 10, 41, 1553.96);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('401 Emmet Circle', 4, 27, 3902.34);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('731 Clarendon Alley', 20, 22, 3504.25);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('6497 Barnett Trail', 38, 35, 3776.13);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('132 Utah Drive', 12, 23, 4109.48);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('5 Lawn Point', 17, 11, 1749.78);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('14346 Kings Crossing', 14, 16, 4276.36);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('11 Scofield Place', 13, 34, 4429.71);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('003 Dryden Terrace', 50, 2, 3712.35);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('589 Dakota Trail', 28, 5, 4057.42);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('939 Mariners Cove Trail', 15, 12, 2485.73);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('4 Myrtle Drive', 16, 12, 4048.67);
insert into dbo.Properties (Address, Owner, Tenant, Rent) values ('81 Burning Wood Plaza', 40, 39, 1625.0);
